### PR TITLE
Rewrite the models with Codable

### PR DESCRIPTION
**Pull request by vpeschenkov**
Hi! I've rewritten the models with `Codable` to simplify json parsing. What do you think about it?

### CODE REVIEW

**Comment by dkhamsing** [comment]
Thank you! Will review later 🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Hey @vpeschenkov 
Travis is not setup correctly but this project doesn't build at the moment

https://travis-ci.org/dkhamsing/osia/builds/342962006?utm_source=github_status&utm_medium=notification
```
...
▸ Compiling CategoryController.swift
▸ Compiling ScreenshotsController.swift
▸ Compiling Content.swift
▸ Compiling AppDelegate.swift
▸ Compiling ScreenshotCell.swift
▸ Linking osia
▸ Compiling LaunchScreen.storyboard
** BUILD FAILED **
The following build commands failed:
	CompileAssetCatalog /Users/travis/Library/Developer/Xcode/DerivedData/osia-dfkleveoagcrggfjdwdmnxihvnnm/Build/Products/Debug-iphonesimulator/osia.app osia/Resoures/Assets.xcassets
(1 failure)
```

**Comment by vpeschenkov** [comment]
Fixed

**Comment by dkhamsing** [comment]
Sorry haven't had time to review, hope to do so soon

**Comment by vpeschenkov** [comment]
Don't worry, it will wait 😊

**Comment by dkhamsing** [comment]
Thank you very much @vpeschenkov!

**Pull request merged**
